name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.6+1
homepage: https://konseben.dev
issue_tracker: https://github.com/btastic/flutter_native_image/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
